#[cfg(all(not(feature = "std"), not(test)))]
use alloc::{borrow::ToOwned, string::String, vec::Vec};
use core::str;

#[cfg(feature = "compact_str")]
use compact_str::CompactString;

use super::DecodeRecord;
use crate::error::{Error, ErrorKind};
use crate::from_bytes::{
    parse_i8, parse_i16, parse_i32, parse_i64, parse_i128, parse_isize, parse_u8, parse_u16,
    parse_u32, parse_u64, parse_u128, parse_usize,
};

/// Decode a single CSV field value from raw bytes.
///
/// The `'record` lifetime allows implementations to borrow directly from the
/// source record without copying. Owned types ignore it.
///
/// This trait is called by [`CsvDecode`](super::CsvDecode) impls generated by the derive macro
/// and can be implemented for custom field types.
/// For a worked example, see [`super::CsvDecode`].
pub trait DecodeField<'record>: Sized {
    /// Parse `bytes` into `Self`.
    ///
    /// `bytes` is `None` when the CSV field is absent (the record is shorter
    /// than expected). Most implementations treat `None` and `Some(b"")`
    /// equivalently; [`Option<T>`] treats both as `None`.
    ///
    /// `index` and `name` are used to construct an [`Error`](crate::Error) on failure.
    ///
    /// # Errors
    ///
    /// Returns an [`Error`](crate::Error) when the bytes cannot be converted to `Self`.
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error>;

    /// Decode field `index` directly from a record, with awareness of
    /// explicit NULL metadata.
    ///
    /// The default implementation ignores NULL-awareness entirely and
    /// simply forwards to [`Self::decode_field`] with `record.get_field(index)`,
    /// so every existing `DecodeField` implementation keeps its current
    /// behavior unchanged. [`Option<T>`] overrides this method: on a
    /// NULL-aware record, an explicit NULL or a missing field decodes to
    /// `None`, while a present (even empty) field decodes to
    /// `Some(T::decode_field(..))` — preserving `Some(<empty>)` for
    /// `Option<String>`/`Option<Vec<u8>>` and the underlying type's parse
    /// error for `Option<numeric>`. On a non-NULL-aware record, `Option<T>`
    /// treats both absent and present-empty fields as `None`.
    ///
    /// Generated `#[derive(CsvDecode)]` code calls this method instead of
    /// [`Self::decode_field`] directly.
    ///
    /// # Errors
    ///
    /// Returns an [`Error`](crate::Error) under the same conditions as
    /// [`Self::decode_field`].
    fn decode_field_from_record<R>(
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        Self::decode_field(record.get_field(index), index, name)
    }

    /// Parse `bytes` into an existing value, reusing its allocations.
    ///
    /// The default implementation is equivalent to
    /// `*self = Self::decode_field(bytes, index, name)?`. [`String`] and
    /// [`Vec<u8>`] override it to overwrite their existing buffer instead of
    /// allocating a new one.
    ///
    /// # Errors
    ///
    /// Returns an [`Error`](crate::Error) under the same conditions as
    /// [`Self::decode_field`]. On failure `self` is left in an unspecified
    /// but valid state.
    fn decode_field_into(
        &mut self,
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error> {
        *self = Self::decode_field(bytes, index, name)?;
        Ok(())
    }

    /// Decode field `index` directly from a record into an existing value,
    /// reusing its allocations.
    ///
    /// The default implementation is equivalent to
    /// `*self = Self::decode_field_from_record(record, index, name)?`, so
    /// every existing implementation keeps its current behavior. Generated
    /// `#[derive(CsvDecode)]` code calls this method from `csv_decode_into`.
    ///
    /// # Errors
    ///
    /// Returns an [`Error`](crate::Error) under the same conditions as
    /// [`Self::decode_field_from_record`]. On failure `self` is left in an
    /// unspecified but valid state.
    fn decode_field_into_from_record<R>(
        &mut self,
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        *self = Self::decode_field_from_record(record, index, name)?;
        Ok(())
    }
}

// &'record [u8] — zero-copy borrow

impl<'record> DecodeField<'record> for &'record [u8] {
    #[inline]
    fn decode_field(
        bytes: Option<&'record [u8]>,
        _index: usize,
        _name: &'static str,
    ) -> Result<Self, Error> {
        Ok(bytes.unwrap_or(b""))
    }
}

// &'record str — zero-copy borrow with UTF-8 validation

/// Build the error for a field that was not valid UTF-8.
///
/// Outlined and cold: inlining `Error` construction made `decode_field` look
/// expensive to LLVM and blocked inlining it into generated decoding bodies,
/// costing 37 instructions per field as an out-of-line call.
#[cold]
#[inline(never)]
fn field_error(kind: ErrorKind, index: usize, name: &'static str) -> Error {
    Error::field(kind, index, Some(name))
}

#[cold]
#[inline(never)]
fn invalid_utf8(error: str::Utf8Error, index: usize, name: &'static str) -> Error {
    Error::field(ErrorKind::InvalidUtf8(error), index, Some(name))
}

// CSV fields are overwhelmingly short and ASCII; screening for ASCII first with
// a word-at-a-time scan avoids the general validator's alignment and
// multi-byte machinery.
#[inline]
fn borrow_utf8(bytes: &[u8]) -> Result<&str, str::Utf8Error> {
    coseva_unsafe::bytes::borrow_utf8(bytes)
}

impl<'record> DecodeField<'record> for &'record str {
    #[inline]
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error> {
        let bytes = bytes.unwrap_or(b"");
        borrow_utf8(bytes).map_err(|e| invalid_utf8(e, index, name))
    }
}

// Vec<u8> — owned copy

fn overwrite_bytes(target: &mut Vec<u8>, bytes: &[u8]) {
    target.clear();
    target.extend_from_slice(bytes);
}

impl<'record> DecodeField<'record> for Vec<u8> {
    fn decode_field(
        bytes: Option<&'record [u8]>,
        _index: usize,
        _name: &'static str,
    ) -> Result<Self, Error> {
        Ok(bytes.unwrap_or(b"").to_vec())
    }

    fn decode_field_into(
        &mut self,
        bytes: Option<&'record [u8]>,
        _index: usize,
        _name: &'static str,
    ) -> Result<(), Error> {
        overwrite_bytes(self, bytes.unwrap_or(b""));
        Ok(())
    }

    fn decode_field_into_from_record<R>(
        &mut self,
        record: &R,
        index: usize,
        _name: &'static str,
    ) -> Result<(), Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        overwrite_bytes(self, record.get_field(index).unwrap_or_default());
        Ok(())
    }
}

// String — owned UTF-8

impl<'record> DecodeField<'record> for String {
    #[inline]
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error> {
        let bytes = bytes.unwrap_or(b"");
        borrow_utf8(bytes)
            .map(str::to_owned)
            .map_err(|e| invalid_utf8(e, index, name))
    }

    #[inline]
    fn decode_field_into(
        &mut self,
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error> {
        let text = borrow_utf8(bytes.unwrap_or(b"")).map_err(|e| invalid_utf8(e, index, name))?;
        self.clear();
        self.push_str(text);
        Ok(())
    }

    fn decode_field_into_from_record<R>(
        &mut self,
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        self.decode_field_into(record.get_field(index), index, name)
    }
}

// CompactString — owned UTF-8, stored inline when short

/// Decodes exactly like [`String`], but a field of 24 bytes or fewer is held
/// inline and allocates nothing.
///
/// CSV fields are very often that short — state codes, currencies, enum-like
/// flags, city names, formatted numbers — so this is the cheaper owned string
/// for most columns, while being no larger than a [`String`].
#[cfg(feature = "compact_str")]
impl<'record> DecodeField<'record> for CompactString {
    #[inline]
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error> {
        let bytes = bytes.unwrap_or(b"");
        borrow_utf8(bytes)
            .map(Self::from)
            .map_err(|e| invalid_utf8(e, index, name))
    }

    #[inline]
    fn decode_field_into(
        &mut self,
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error> {
        let text = borrow_utf8(bytes.unwrap_or(b"")).map_err(|e| invalid_utf8(e, index, name))?;
        self.clear();
        self.push_str(text);
        Ok(())
    }

    fn decode_field_into_from_record<R>(
        &mut self,
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        self.decode_field_into(record.get_field(index), index, name)
    }
}

// bool — byte-native "true"/"false" and "1"/"0"

impl<'record> DecodeField<'record> for bool {
    #[inline]
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error> {
        match bytes.unwrap_or(b"") {
            b"true" | b"1" => Ok(true),
            b"false" | b"0" => Ok(false),
            _ => Err(field_error(ErrorKind::InvalidValue, index, name)),
        }
    }
}

macro_rules! impl_decode_field_integer {
    ($(($ty:ty, $parse:ident)),+ $(,)?) => {
        $(
            impl<'record> DecodeField<'record> for $ty {
                #[inline]
                fn decode_field(
                    bytes: Option<&'record [u8]>,
                    index: usize,
                    name: &'static str,
                ) -> Result<Self, Error> {
                    let bytes = bytes.unwrap_or(b"");
                    $parse(bytes).map_err(|kind| field_error(kind, index, name))
                }
            }
        )+
    };
}

impl_decode_field_integer!(
    (i8, parse_i8),
    (i16, parse_i16),
    (i32, parse_i32),
    (i64, parse_i64),
    (i128, parse_i128),
    (isize, parse_isize),
    (u8, parse_u8),
    (u16, parse_u16),
    (u32, parse_u32),
    (u64, parse_u64),
    (u128, parse_u128),
    (usize, parse_usize),
);

/// Floats parse straight from raw bytes; an empty field is reported as
/// [`ErrorKind::EmptyField`] and any other rejection as
/// [`ErrorKind::InvalidValue`], matching the [`crate::FromBytes`] impls.
macro_rules! impl_decode_field_float {
    ($($ty:ty),+ $(,)?) => {
        $(
            impl<'record> DecodeField<'record> for $ty {
                #[inline]
                fn decode_field(
                    bytes: Option<&'record [u8]>,
                    index: usize,
                    name: &'static str,
                ) -> Result<Self, Error> {
                    let bytes = bytes.unwrap_or(b"");
                    fast_float2::parse(bytes).map_err(|_error| {
                        let kind = if bytes.is_empty() {
                            ErrorKind::EmptyField
                        } else {
                            ErrorKind::InvalidValue
                        };
                        Error::field(kind, index, Some(name))
                    })
                }
            }
        )+
    };
}

impl_decode_field_float!(f32, f64);

// Option<T> — None for absent or empty fields

impl<'record, T: DecodeField<'record>> DecodeField<'record> for Option<T> {
    fn decode_field(
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error> {
        match bytes {
            None | Some(b"") => Ok(None),
            Some(b) => T::decode_field(Some(b), index, name).map(Some),
        }
    }

    fn decode_field_from_record<R>(
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<Self, Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        if record.is_null_aware() {
            if record.is_field_null(index) {
                return Ok(None);
            }
            match record.get_field(index) {
                None => Ok(None),
                bytes @ Some(_) => T::decode_field(bytes, index, name).map(Some),
            }
        } else {
            Self::decode_field(record.get_field(index), index, name)
        }
    }

    fn decode_field_into(
        &mut self,
        bytes: Option<&'record [u8]>,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error> {
        match bytes {
            None | Some(b"") => {
                drop(self.take());
                Ok(())
            }
            Some(_) => decode_some_into(self, bytes, index, name),
        }
    }

    fn decode_field_into_from_record<R>(
        &mut self,
        record: &R,
        index: usize,
        name: &'static str,
    ) -> Result<(), Error>
    where
        R: DecodeRecord<'record> + ?Sized,
    {
        if !record.is_null_aware() {
            return self.decode_field_into(record.get_field(index), index, name);
        }
        if record.is_field_null(index) {
            drop(self.take());
            return Ok(());
        }
        match record.get_field(index) {
            None => {
                drop(self.take());
                Ok(())
            }
            bytes @ Some(_) => decode_some_into(self, bytes, index, name),
        }
    }
}

/// Decode a present field into `slot`, reusing the existing inner value when
/// one is already present.
fn decode_some_into<'record, T>(
    slot: &mut Option<T>,
    bytes: Option<&'record [u8]>,
    index: usize,
    name: &'static str,
) -> Result<(), Error>
where
    T: DecodeField<'record>,
{
    if let Some(inner) = slot.as_mut() {
        inner.decode_field_into(bytes, index, name)
    } else {
        *slot = Some(T::decode_field(bytes, index, name)?);
        Ok(())
    }
}

// ── EncodeField ────────────────────────────────────────────────────────────────

/// Decodes a `#[csv(default)]` field, using [`Default::default()`] when absent
/// or empty.
///
/// For a worked example, see [`super::CsvDecode`].
///
/// # Errors
///
/// Returns an [`Error`](crate::Error) when the field is present and non-empty but
/// cannot be converted to `T`.
pub fn decode_field_or_default<'record, T>(
    bytes: Option<&'record [u8]>,
    index: usize,
    name: &'static str,
) -> Result<T, Error>
where
    T: DecodeField<'record> + Default,
{
    match bytes {
        None | Some(b"") => Ok(T::default()),
        Some(b) => T::decode_field(Some(b), index, name),
    }
}

#[cfg_attr(coverage_nightly, coverage(off))]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::byte_record::ByteRecord;
    use crate::encoding::decode_record::ByteRecordRef;

    struct CustomField(u32);
    impl<'record> DecodeField<'record> for CustomField {
        fn decode_field(
            bytes: Option<&'record [u8]>,
            index: usize,
            name: &'static str,
        ) -> Result<Self, Error> {
            let val = u32::decode_field(bytes, index, name)?;
            Ok(Self(val))
        }
    }

    #[derive(Debug, Default, Eq, PartialEq)]
    struct AlwaysInvalid;

    impl<'record> DecodeField<'record> for AlwaysInvalid {
        fn decode_field(
            _bytes: Option<&'record [u8]>,
            index: usize,
            name: &'static str,
        ) -> Result<Self, Error> {
            Err(Error::field(ErrorKind::InvalidValue, index, Some(name)))
        }
    }

    fn assert_field_error(error: &Error, index: usize, name: &'static str) {
        assert_eq!(error.location().field, index);
        assert_eq!(error.field_name(), Some(name));
    }

    struct NullAwareEmpty;

    impl<'record> DecodeRecord<'record> for NullAwareEmpty {
        fn get_field(&self, index: usize) -> Option<&'record [u8]> {
            (index == 0).then_some(b"")
        }

        fn is_null_aware(&self) -> bool {
            true
        }
    }

    #[test]
    fn test_decode_field_into_from_record() {
        let mut direct = b"stale".to_vec();
        direct
            .decode_field_into(Some(b"fresh"), 0, "bytes_field")
            .expect("decodes bytes directly");
        assert_eq!(direct, b"fresh");

        let mut rec = ByteRecord::new();
        rec.push_field(b"bytes_field");
        rec.push_field(b"str_field");
        rec.push_field(b"123");

        let r = ByteRecordRef::new(&rec);

        let mut v = b"stale".to_vec();
        v.decode_field_into_from_record(&r, 0, "bytes_field")
            .expect("decodes bytes");
        assert_eq!(v, b"bytes_field");

        let mut s = String::new();
        s.decode_field_into_from_record(&r, 1, "str_field")
            .expect("decodes str");
        assert_eq!(s, "str_field");

        let custom =
            CustomField::decode_field_from_record(&r, 2, "custom").expect("decodes custom");
        assert_eq!(custom.0, 123);

        let mut custom_target = CustomField(0);
        custom_target
            .decode_field_into(Some(b"456"), 2, "custom")
            .expect("decodes into custom");
        assert_eq!(custom_target.0, 456);

        custom_target
            .decode_field_into_from_record(&r, 2, "custom")
            .expect("decodes into custom from record");
        assert_eq!(custom_target.0, 123);

        // Error branches for default decode_field_into and decode_field_into_from_record
        assert!(
            custom_target
                .decode_field_into(Some(b"not_a_number"), 2, "custom")
                .is_err()
        );
        let mut bad_rec = ByteRecord::new();
        bad_rec.push_field(b"not_a_number");
        let bad_r = ByteRecordRef::new(&bad_rec);
        assert!(
            custom_target
                .decode_field_into_from_record(&bad_r, 0, "custom")
                .is_err()
        );

        let mut s_err = String::new();
        assert!(
            s_err
                .decode_field_into(Some(b"\xff\xff"), 0, "bad")
                .is_err()
        );
    }

    #[test]
    fn conversion_errors_preserve_the_supplied_field_identity() {
        let mut default_into = AlwaysInvalid;
        let default_into_error = default_into
            .decode_field_into(Some(b"x"), 6, "default_into")
            .expect_err("default in-place conversion fails");
        assert_field_error(&default_into_error, 6, "default_into");

        let invalid_utf8 = <&str as DecodeField<'_>>::decode_field(Some(b"\xff"), 7, "borrowed")
            .expect_err("invalid UTF-8");
        assert_field_error(&invalid_utf8, 7, "borrowed");

        let mut owned = String::new();
        let invalid_owned = owned
            .decode_field_into(Some(b"\xff"), 8, "owned")
            .expect_err("invalid UTF-8");
        assert_field_error(&invalid_owned, 8, "owned");

        let invalid_bool =
            bool::decode_field(Some(b"maybe"), 9, "flag").expect_err("invalid boolean");
        assert_field_error(&invalid_bool, 9, "flag");

        let invalid_integer =
            u32::decode_field(Some(b"nope"), 10, "count").expect_err("invalid integer");
        assert_field_error(&invalid_integer, 10, "count");

        #[cfg(feature = "compact_str")]
        {
            let mut compact = CompactString::default();
            let invalid_compact = compact
                .decode_field_into(Some(b"\xff"), 11, "compact")
                .expect_err("invalid UTF-8");
            assert_field_error(&invalid_compact, 11, "compact");
        }
    }

    #[test]
    fn record_based_owned_string_errors_preserve_the_requested_index() {
        let mut record = ByteRecord::new();
        record.push_field(b"valid");
        record.push_field(b"\xff");
        let record = ByteRecordRef::new(&record);

        let mut owned = String::new();
        let error = owned
            .decode_field_into_from_record(&record, 1, "owned")
            .expect_err("invalid UTF-8");
        assert_field_error(&error, 1, "owned");

        #[cfg(feature = "compact_str")]
        {
            let mut compact = CompactString::default();
            let error = compact
                .decode_field_into_from_record(&record, 1, "compact")
                .expect_err("invalid UTF-8");
            assert_field_error(&error, 1, "compact");
        }
    }

    #[test]
    fn option_paths_preserve_indices_and_null_aware_empty_fields() {
        let mut present_empty = Some(String::from("stale"));
        present_empty
            .decode_field_into_from_record(&NullAwareEmpty, 0, "empty")
            .expect("present empty field");
        assert_eq!(present_empty, Some(String::new()));

        assert_eq!(
            Option::<String>::decode_field_from_record(&NullAwareEmpty, 0, "empty")
                .expect("present empty field"),
            Some(String::new())
        );

        let direct = Option::<AlwaysInvalid>::decode_field(Some(b"x"), 12, "direct")
            .expect_err("inner conversion fails");
        assert_field_error(&direct, 12, "direct");

        let mut occupied = Some(AlwaysInvalid);
        let error = occupied
            .decode_field_into(Some(b"x"), 13, "occupied")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 13, "occupied");

        let mut vacant: Option<AlwaysInvalid> = None;
        let error = vacant
            .decode_field_into(Some(b"x"), 14, "vacant")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 14, "vacant");

        let defaulted = decode_field_or_default::<AlwaysInvalid>(Some(b"x"), 15, "defaulted")
            .expect_err("inner conversion fails");
        assert_field_error(&defaulted, 15, "defaulted");

        let mut ordinary = ByteRecord::new();
        ordinary.push_field(b"x");
        let ordinary = ByteRecordRef::new(&ordinary);
        let error = Option::<AlwaysInvalid>::decode_field_from_record(&ordinary, 0, "ordinary")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 0, "ordinary");
        let mut ordinary_slot = Some(AlwaysInvalid);
        let error = ordinary_slot
            .decode_field_into_from_record(&ordinary, 0, "ordinary_into")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 0, "ordinary_into");

        let mut nullable = ByteRecord::new();
        nullable.push_field(b"prefix");
        nullable.push_null();
        nullable.push_field(b"");
        nullable.push_field(b"x");
        let nullable = ByteRecordRef::new(&nullable);

        assert_eq!(
            Option::<String>::decode_field_from_record(&nullable, 2, "empty")
                .expect("present empty field"),
            Some(String::new())
        );
        let error = Option::<AlwaysInvalid>::decode_field_from_record(&nullable, 3, "nullable")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 3, "nullable");
        let mut nullable_slot = Some(AlwaysInvalid);
        let error = nullable_slot
            .decode_field_into_from_record(&nullable, 3, "nullable_into")
            .expect_err("inner conversion fails");
        assert_field_error(&error, 3, "nullable_into");

        let mut cleared = Some(String::from("old"));
        cleared
            .decode_field_into_from_record(&nullable, 1, "null")
            .expect("explicit null");
        assert_eq!(cleared, None);
        cleared = Some(String::from("old"));
        cleared
            .decode_field_into_from_record(&nullable, 99, "missing")
            .expect("missing field");
        assert_eq!(cleared, None);
    }

    #[test]
    #[cfg(feature = "compact_str")]
    fn test_decode_compact_str() {
        let mut rec = ByteRecord::new();
        rec.push_field(b"bytes_field");
        rec.push_field(b"str_field");
        let r = ByteRecordRef::new(&rec);

        let mut cs = CompactString::default();
        cs.decode_field_into_from_record(&r, 1, "str_field")
            .expect("decodes compact str");
        assert_eq!(cs, "str_field");

        let mut cs_err = CompactString::default();
        assert!(
            cs_err
                .decode_field_into(Some(b"\xff\xff"), 0, "bad")
                .is_err()
        );
    }
}
