#[cfg(all(not(feature = "std"), not(test)))]
use alloc::{string::String, vec::Vec};

#[cfg(feature = "compact_str")]
use compact_str::CompactString;

use super::EncodeVisitor;
use crate::error::Error;

/// Encode a single field value into raw bytes via an [`EncodeVisitor`].
///
/// This trait is called by [`CsvEncode`](super::CsvEncode) impls generated by the derive macro
/// and can be implemented for custom field types.
/// For a worked example, see [`super::CsvEncode`].
pub trait EncodeField {
    /// Encode `self` and pass the resulting bytes to `visitor`.
    ///
    /// `index` is the zero-based field location. `name` is the static
    /// field name. The bytes passed to the visitor must not include any
    /// quoting or escaping; the emitter layer handles that.
    ///
    /// # Errors
    ///
    /// Returns an [`Error`](crate::Error) when the visitor rejects the field.
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error>;
}

// [u8] — pass bytes directly

impl EncodeField for [u8] {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self)
    }
}

// &[u8] — deref and pass

impl EncodeField for &[u8] {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self)
    }
}

// Vec<u8>

impl EncodeField for Vec<u8> {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self.as_slice())
    }
}

// str — pass UTF-8 bytes

impl EncodeField for str {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self.as_bytes())
    }
}

// &str

impl EncodeField for &str {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self.as_bytes())
    }
}

// String

impl EncodeField for String {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self.as_bytes())
    }
}

// CompactString

/// Encodes exactly like [`String`], which a [`CompactString`] field of 24 bytes
/// or fewer reaches without ever having allocated.
#[cfg(feature = "compact_str")]
impl EncodeField for CompactString {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, self.as_bytes())
    }
}

// bool

impl EncodeField for bool {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        visitor.visit_field(index, name, if *self { b"true" } else { b"false" })
    }
}

// Integer types use a stack buffer.

macro_rules! impl_encode_field_integer {
    ($($ty:ty),+ $(,)?) => {
        $(
            impl EncodeField for $ty {
                fn encode_to<V: EncodeVisitor>(
                    &self,
                    index: usize,
                    name: &'static str,
                    visitor: &mut V,
                ) -> Result<(), Error> {
                    let mut buffer = itoa::Buffer::new();
                    visitor.visit_field(index, name, buffer.format(*self).as_bytes())
                }
            }
        )+
    };
}

impl_encode_field_integer!(
    i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize
);

// Floating-point types use Ryu's shortest round-trippable stack format.

macro_rules! impl_encode_field_float {
    ($($ty:ty),+ $(,)?) => {
        $(
            impl EncodeField for $ty {
                fn encode_to<V: EncodeVisitor>(
                    &self,
                    index: usize,
                    name: &'static str,
                    visitor: &mut V,
                ) -> Result<(), Error> {
                    let mut buffer = ryu::Buffer::new();
                    visitor.visit_field(index, name, buffer.format(*self).as_bytes())
                }
            }
        )+
    };
}

impl_encode_field_float!(f32, f64);

// Option<T> — empty field for None

impl<T: EncodeField> EncodeField for Option<T> {
    fn encode_to<V: EncodeVisitor>(
        &self,
        index: usize,
        name: &'static str,
        visitor: &mut V,
    ) -> Result<(), Error> {
        match self {
            None => visitor.visit_null(index, name),
            Some(val) => val.encode_to(index, name, visitor),
        }
    }
}
